<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DAPATKAN SEKARANG</name>
   <tag></tag>
   <elementGuidId>b165ecff-0755-4047-b392-b1588056c6b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save-financial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-financial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3a3b8a41-2d05-495c-812e-a909c8b51507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-financial</value>
      <webElementGuid>a5c0af2d-a8fb-4631-9b78-93278db3e7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>99659da0-d1da-42cd-8029-1791499272e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary</value>
      <webElementGuid>478b4a8f-03bf-4e9b-8427-683dfbeebef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAPATKAN SEKARANG</value>
      <webElementGuid>e00f28f8-423f-4c41-938f-c39f5927881f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-financial&quot;)</value>
      <webElementGuid>58ef0e17-1678-43fc-b3c3-3b2c4f26d31d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-financial']</value>
      <webElementGuid>6d782dc6-513c-4849-9399-a4d913ff8883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='button-klik']/button</value>
      <webElementGuid>515af7fd-4ceb-44ba-8f30-f97052e0e80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya bersedia dihubungi untuk mendapatkan informasi selanjutnya dari Sequis'])[1]/following::button[1]</value>
      <webElementGuid>71fcb03d-b774-420c-ae24-15004b0a6040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACEH SELATAN'])[2]/following::button[1]</value>
      <webElementGuid>e22ee26c-e9da-49fa-bdd4-90f874ed5c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF sudah dikirimkan ke email Anda'])[1]/preceding::button[2]</value>
      <webElementGuid>b32ef45e-addd-4fef-82be-1bce7e4d1250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terima Kasih telah menghubungi Kami'])[1]/preceding::button[2]</value>
      <webElementGuid>62b00f39-9383-4820-9591-b61e0926bf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAPATKAN SEKARANG']/parent::*</value>
      <webElementGuid>08b56696-cb1e-4013-bb32-cd0d9e9b0a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[7]/div/button</value>
      <webElementGuid>e1df4510-8eb2-464a-bad4-8869b5d72d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save-financial' and @type = 'submit' and (text() = 'DAPATKAN SEKARANG' or . = 'DAPATKAN SEKARANG')]</value>
      <webElementGuid>d67a0c3d-e27a-4c38-8f57-31c5e851a610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
