<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ACEH SELATAN_bersedia</name>
   <tag></tag>
   <elementGuidId>27c8528e-418c-4e2f-9cdd-e67f109d9d10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bersedia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bersedia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>633c065b-e7ec-4ccc-9b2a-07e42e5d4b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>9552c913-d522-4a65-ad87-4bfd624dd1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>639b5a02-93c5-49ce-8a52-19876b5d9981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bersedia</value>
      <webElementGuid>15d709d0-e04f-4aaa-8252-1c8bb51a4a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bersedia</value>
      <webElementGuid>c15a94f4-e1d3-4874-aef8-6edd401e8ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bersedia&quot;)</value>
      <webElementGuid>0d38649b-e32d-47eb-9c50-4c820c292651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bersedia']</value>
      <webElementGuid>5ffccc69-cd11-4f8a-bea7-055d1528d77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert-financial']/div[6]/span/input</value>
      <webElementGuid>d2692758-b4dd-4774-9425-b0962b97addd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/input</value>
      <webElementGuid>b7feced0-36d0-48be-8ddd-b690c795d87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'bersedia' and @id = 'bersedia']</value>
      <webElementGuid>c3ec4403-6ca4-4884-ba36-5f0277975348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
