<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Silahkan Pilih --ACEH BARATACEH B_d4ce56</name>
   <tag></tag>
   <elementGuidId>64eadaf9-7e1b-45ac-a507-59d2ec392fed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6b29fa6-8860-4d7f-8937-989e58d3c732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>bf11dae6-7a53-493c-9702-3f7c68ee0f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>78ef5665-8668-42d4-bc9b-931e989920dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl jcf-reset-appearance</value>
      <webElementGuid>3fc8aff6-63b9-4c00-a0ea-048da18fa353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Silahkan Pilih --ACEH BARATACEH BARAT DAYAACEH BESARACEH JAYAACEH SELATANACEH SINGKILACEH TAMIANGACEH TENGAHACEH TENGGARAACEH TIMURACEH UTARABENER MERIAHBIREUENGAYO LUESKOTA BANDA ACEHKOTA LANGSAKOTA LHOKSEUMAWEKOTA SABANGKOTA SUBULUSSALAMNAGAN RAYAPIDIEPIDIE JAYASIMEULUE</value>
      <webElementGuid>31c33a58-2122-460b-bb19-a9601cc59194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>eb8b7e3d-4201-4c52-a2e5-b7f464009017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>ff7e5038-e223-44c0-a310-c0368aa4efa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert-financial']/div[5]/span/select</value>
      <webElementGuid>e369e7f3-2ee5-4b65-9c12-901d79996d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/following::select[1]</value>
      <webElementGuid>757fb62c-17fe-43af-b9fe-21ed8c9e639c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACEH'])[2]/following::select[1]</value>
      <webElementGuid>aa6b9444-57af-4d0a-8273-43a627d6c9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Silakan pilih --'])[2]/preceding::select[1]</value>
      <webElementGuid>c627b2a2-1804-4724-9644-b4a3f27c2239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya bersedia dihubungi untuk mendapatkan informasi selanjutnya dari Sequis'])[1]/preceding::select[1]</value>
      <webElementGuid>00213b5b-d418-49f5-aef6-25be597ba8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/select</value>
      <webElementGuid>b7a68b4b-8430-429d-bb56-f79ede103a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'city' and @id = 'city' and (text() = '-- Silahkan Pilih --ACEH BARATACEH BARAT DAYAACEH BESARACEH JAYAACEH SELATANACEH SINGKILACEH TAMIANGACEH TENGAHACEH TENGGARAACEH TIMURACEH UTARABENER MERIAHBIREUENGAYO LUESKOTA BANDA ACEHKOTA LANGSAKOTA LHOKSEUMAWEKOTA SABANGKOTA SUBULUSSALAMNAGAN RAYAPIDIEPIDIE JAYASIMEULUE' or . = '-- Silahkan Pilih --ACEH BARATACEH BARAT DAYAACEH BESARACEH JAYAACEH SELATANACEH SINGKILACEH TAMIANGACEH TENGAHACEH TENGGARAACEH TIMURACEH UTARABENER MERIAHBIREUENGAYO LUESKOTA BANDA ACEHKOTA LANGSAKOTA LHOKSEUMAWEKOTA SABANGKOTA SUBULUSSALAMNAGAN RAYAPIDIEPIDIE JAYASIMEULUE')]</value>
      <webElementGuid>cc003481-4fd4-4fba-bd1a-28629a8b2080</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
