<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya Page 3</name>
   <tag></tag>
   <elementGuidId>2d5b49e9-b2e3-4895-a689-83bacf62e77d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#financial-pensiun-step3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='financial-pensiun-step3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae26d28c-a7d0-4734-8b4f-1a73f47a896f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd110efc-8d2e-448d-b804-ab766a78086e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary</value>
      <webElementGuid>d4a36c76-87b0-4f01-b0bd-6383753a2ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>financial-pensiun-step3</value>
      <webElementGuid>3c8a9cc0-ce11-4700-bd2d-62fe202b85cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>f5badd89-bcff-4656-b05e-91209fbba147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;financial-pensiun-step3&quot;)</value>
      <webElementGuid>d9c552d8-3235-4a1c-b98b-73f25ced614f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='financial-pensiun-step3']</value>
      <webElementGuid>10d0357c-3008-4be6-b310-23b9602ef97f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[3]/div[4]/button</value>
      <webElementGuid>97d14747-9e57-4748-8daf-f2f033b001f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rasio Penggantian yang dikehendaki (%)'])[1]/following::button[1]</value>
      <webElementGuid>daea76d5-5ad2-44ff-9f9c-cf6d54068bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah pemasukan saat mencapai usia pensiun yang Anda inginkan'])[1]/preceding::button[1]</value>
      <webElementGuid>8d0c02d0-681f-4141-a95b-dbf8e90d23b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemasukan pada saat usia pensiun'])[1]/preceding::button[1]</value>
      <webElementGuid>8f2b795a-c691-4b49-9fc9-e82649c3fa3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[4]/button</value>
      <webElementGuid>955625a3-0ba9-4986-beae-e4d8e1a54c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'financial-pensiun-step3' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>50b689c0-4906-4727-8c1a-a0a370b00530</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
