<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya Page 4</name>
   <tag></tag>
   <elementGuidId>ffcc7f7c-0a15-4da7-81a9-288de8e848b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#financial-pensiun-step4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='financial-pensiun-step4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ad933ad-94db-4107-9a49-f6f01b49f667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5b147487-33a2-4010-906e-7f87d48ba292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary</value>
      <webElementGuid>726eb0aa-466d-475a-9896-9a1d671148c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>financial-pensiun-step4</value>
      <webElementGuid>9a848f0a-1cf2-4835-9e36-f9aa2a6ee777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>4471e2b5-ef7d-4c98-a9f7-324f5ce09a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;financial-pensiun-step4&quot;)</value>
      <webElementGuid>441a39f4-7f05-4d47-8ee6-a0a649534897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='financial-pensiun-step4']</value>
      <webElementGuid>c433bb1c-9551-457c-b3f0-6fe88f218b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[4]/div[4]/button</value>
      <webElementGuid>e271c3c6-320a-4fe6-aed8-2b707d5b3f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lama pensiun yang Anda inginkan (Tahun)'])[1]/following::button[1]</value>
      <webElementGuid>c90e987c-cf22-4571-9897-b9304e84b3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[5]/preceding::button[1]</value>
      <webElementGuid>a2aa14f3-9ae0-484e-a6f3-1d999229ede3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tingkat inflasi'])[1]/preceding::button[2]</value>
      <webElementGuid>d53275d3-487b-4e7f-a81d-d0791ac4af09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div[4]/button</value>
      <webElementGuid>ebe189a4-7d19-40f8-a216-b60291fb8c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'financial-pensiun-step4' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>2aefa3c7-e6ea-418b-8da8-33cd1b68d9b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
