<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lama pensiun yang Anda inginkan (Tahu_dfb7f7</name>
   <tag></tag>
   <elementGuidId>fc2bc094-c7c3-47c6-83ee-9eb8fef70761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pensiunInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pensiunInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d614b1fe-bfbc-411f-adae-daaa93d86b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>271e7c6b-0ad7-4266-9d7a-fced4902b748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>b3740d09-973d-44d2-90aa-6c308af48329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pensiunInput</value>
      <webElementGuid>c02797b6-2c7c-4d7c-9d40-8a8c780e696d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d9122804-05f7-4d2a-9623-167fc9826ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>92f9558e-5bc5-4c82-826b-24c7f2e92c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>47d79aee-29d8-48bc-9996-dab77a30da9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pensiunInput&quot;)</value>
      <webElementGuid>a69a30af-b08c-4611-a74a-39416367a510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pensiunInput']</value>
      <webElementGuid>aed02606-494e-4bf3-a7d2-d97b8ccd5a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[4]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>ab7d411c-0b69-4db1-af42-7820cf8a65df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>6d9de5ef-03a8-4ed2-ba16-26fa400133b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'pensiunInput']</value>
      <webElementGuid>f5d2984b-d69c-408b-a439-8b7f077c304b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
