<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usia Pensiun yang Anda Inginkan (Tahu_a5afd5</name>
   <tag></tag>
   <elementGuidId>5ad971a5-64e2-4878-b64b-bc5a4ac0d5fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usiaPensiunInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usiaPensiunInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>872fe702-e4c7-4654-9deb-e25a5e987a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b784a7e5-06eb-4ec1-a41f-838a84a1b2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>7cc6f24f-86ea-4977-9dbf-a635528eb90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>7b21bc75-ce90-47b6-a9f6-c4a30d084840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>f0e50983-6d21-4da2-accc-b2218d9b4737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usiaPensiunInput</value>
      <webElementGuid>61e0299f-6082-49b7-aa03-b6e4c73b7d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>d4488a8c-cfbc-48ac-b624-30248c3acd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usiaPensiunInput&quot;)</value>
      <webElementGuid>58e7d079-b040-4b5d-9903-4d40e2195142</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usiaPensiunInput']</value>
      <webElementGuid>e8f6a0ed-3578-437b-8756-bcaac9ec95bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[2]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>c669444d-4d7f-4410-b808-438e3a4314e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>a2545f52-20b6-4282-94a4-3cfb7c34c550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'usiaPensiunInput']</value>
      <webElementGuid>3ae4353a-d188-4bec-b30f-820fd6b761be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
