<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rasio Penggantian yang dikehendaki ()_b56598</name>
   <tag></tag>
   <elementGuidId>7e8c6a7c-f74f-4237-86a9-f7100b03644c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ratioInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ratioInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47f21f73-c9d6-4585-9ae9-7617b35bdc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e18c6ae0-10c6-4eff-8122-cd0ed83e0855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>c2813e42-b744-4081-a119-3616237d787f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ratioInput</value>
      <webElementGuid>b067ffa9-6474-4f7a-9bca-dbdf071c8fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>9691657e-5e5b-42b5-97f9-f47cd6be22ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>125</value>
      <webElementGuid>e65a3b21-ad52-4c29-baee-91aebffded96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>5feb2f5b-2603-4c63-a81e-b0c79cd3d6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ratioInput&quot;)</value>
      <webElementGuid>f2143fac-706a-4096-980a-8d087b9a1580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ratioInput']</value>
      <webElementGuid>aecb88e0-6025-4d39-bcf6-79f4bf58c87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[3]/div[3]/div/div/div/input</value>
      <webElementGuid>1e3564c3-1fbf-473b-8e77-e6bafa69d8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[3]/div/div/div/input</value>
      <webElementGuid>2b04a351-3681-40fc-a4cf-37e59c2f8336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'ratioInput']</value>
      <webElementGuid>8efcf8a6-d06e-4a2d-899f-ba3efa682f53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
