<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usia Anda Saat Ini                   _8130c6</name>
   <tag></tag>
   <elementGuidId>6c78225a-49d0-4c1d-ae64-a2a13a07e02a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usiaCurrentInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usiaCurrentInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ffdf8aa-330c-4726-b6d1-f09cac660983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8f06239b-432b-4220-b718-92f0948bbe54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>40640491-5724-4e84-bdc4-7c1249394730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>1dd4419f-0a48-47dc-a909-b7449e8f5459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>24359471-a448-4377-a6b1-d062d6e26641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usiaCurrentInput</value>
      <webElementGuid>03fa14d3-f806-4d21-b056-e4366f7c69d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>bcb7999b-dcbe-4f48-a36b-1031a07622b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usiaCurrentInput&quot;)</value>
      <webElementGuid>320679ea-5df6-44f8-9797-3b871ca8555e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usiaCurrentInput']</value>
      <webElementGuid>c86ba0b0-cd70-48ea-8033-9668837ae186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[2]/div[3]/div/div/div/input</value>
      <webElementGuid>9a9c6418-05e2-4a0a-8daa-3d28d9a0d2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>6337b49e-91aa-49f4-b3d2-a686c12105f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'usiaCurrentInput']</value>
      <webElementGuid>510b55b9-81c5-4046-80f6-2b0c11fbfbc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
