<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suku Bunga Deposito                  _87bd1f</name>
   <tag></tag>
   <elementGuidId>06be501d-5ac4-4030-8c7c-a9180d6bab2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bungaDepositoInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bungaDepositoInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>283e27e3-63fb-479e-8d1f-dc11f3f52387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>90005113-8caf-4533-8aba-436930e738ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>ba266d51-69c2-488a-9eb3-f87915869262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bungaDepositoInput</value>
      <webElementGuid>eb2c8f3a-4810-4c50-be13-a862709ab9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>235bc7e1-be9f-4266-a066-a9bab775db3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>359fd77a-4706-461e-a466-168fede27530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>45fad26c-7049-4ef7-90ce-ffb2207e2e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bungaDepositoInput&quot;)</value>
      <webElementGuid>a62fb454-483b-485b-969e-8483e3936980</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bungaDepositoInput']</value>
      <webElementGuid>e254cd29-1720-4ca4-9a98-75e2c0f3a27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[4]/div[3]/div[3]/div/div/input</value>
      <webElementGuid>880ee765-3e4f-4863-8678-e27d4b945da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>85c340c7-6867-4f88-b5e1-438c84b2e245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'bungaDepositoInput']</value>
      <webElementGuid>3096f458-24ea-434d-82f0-b799f0e32c33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
