<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tingkat inflasi ()_inflasiInput</name>
   <tag></tag>
   <elementGuidId>a266e37f-9acb-4a2c-a340-eec5632e97bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inflasiInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inflasiInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b185fa6e-86cb-4342-852d-ca96a0f721a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7a053a9b-6202-483b-a920-cde3a78248ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formNumeric</value>
      <webElementGuid>9b936d51-7181-4f4a-8bf7-4f87d19aea36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1ad98162-f2bb-44d1-bda1-044c9b991b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>82083607-715f-4c4c-a7ff-3f8ce9dbbefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inflasiInput</value>
      <webElementGuid>c441527c-9668-4f90-9159-e0520b5af527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ef6c9e3b-e5aa-4372-95e2-34d1dbd08179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inflasiInput&quot;)</value>
      <webElementGuid>1968c41b-531d-4e16-9a22-4645a93e2b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inflasiInput']</value>
      <webElementGuid>b9e31bbd-f4a0-4403-a029-b906e49cb2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section/div[3]/div/div/div/div[3]/input</value>
      <webElementGuid>b7fd1279-bdf5-4509-9d3b-f045bb54f2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b1b73a65-e316-4c3d-9035-b95c5398a56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'inflasiInput']</value>
      <webElementGuid>f2f1192d-497f-44d1-a637-4a63c7287ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
