<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_calc_type3</name>
   <tag></tag>
   <elementGuidId>44eeee6c-66e4-4d6e-aac7-f987351ac671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;calc_type3&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='calc_type3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2aab0b08-e884-496d-bd08-268bba60ab14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a1a345b-c517-47db-8d15-1ffb0c4d9339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>calc_type3</value>
      <webElementGuid>b2c32a98-bce9-4e14-8ae8-2c5ebf181bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>calc_type3</value>
      <webElementGuid>1cdf9f6a-7c8f-41eb-9cc6-1a1ec52860ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formMoney currency</value>
      <webElementGuid>bfc06511-003b-4324-b7ed-83ac42a0404d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Penghasilan Per Bulan</value>
      <webElementGuid>b3f1b8f9-cfb3-43db-9ca4-2baec7521ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;financialCalculatePensiun&quot;)/section[@class=&quot;body-step body-step--1 current&quot;]/div[@class=&quot;content-finder form form--finder&quot;]/div[@class=&quot;content-finder__box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row row-0&quot;]/div[@class=&quot;col-md-11 col-kurs col-xs-12&quot;]/input[@class=&quot;form-control formMoney currency&quot;]</value>
      <webElementGuid>beb3d4d5-e80b-4ca6-a64d-4bc334925192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='calc_type3']</value>
      <webElementGuid>e62bb82c-6009-4d2a-b973-bc53706305d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section/div[3]/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>4fefd82f-9c23-4914-9829-f82884922aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>aa881497-a143-4aa4-902e-4cf36bf1e4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'calc_type3' and @placeholder = 'Penghasilan Per Bulan']</value>
      <webElementGuid>49a816cc-1940-45af-bf42-3ef32f2195b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
