<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Cookies</name>
   <tag></tag>
   <elementGuidId>abfd02ab-26ec-4c96-82fa-dc3a3e765657</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pc-button > button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pc-button']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac3409fa-873c-4acd-8d9b-1cb8c040068f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-content</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>37414567-8110-4d86-bea1-027db3b30b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pc-button&quot;)/button[1]</value>
      <webElementGuid>604a042e-167f-49e7-8c9f-74a7ac96a4b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pc-button']/button</value>
      <webElementGuid>b3da5b77-a1b5-4891-9391-1ba97d380291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>95082811-61e4-43cf-93c1-e46a179ed288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
