<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DAPATKAN SEKARANG</name>
   <tag></tag>
   <elementGuidId>00898032-ce90-45ef-8948-7a29da69466d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save-financial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-financial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>773d37a8-c154-4c77-8d46-71f166b09adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-financial</value>
      <webElementGuid>70f6cd19-29f3-40a1-9cff-5d25a02a7944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>af6b7286-6c4b-42a3-bfda-1a6651a3e574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary</value>
      <webElementGuid>bd90b431-a502-4f1b-ad9f-7f29f556384c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAPATKAN SEKARANG</value>
      <webElementGuid>d4de931f-134f-4be1-b5d6-79f48890a7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-financial&quot;)</value>
      <webElementGuid>57edfb14-0860-4504-80d1-041fd1a8d630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-financial']</value>
      <webElementGuid>c82b01fb-f553-48a7-930d-9fda578247cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='button-klik']/button</value>
      <webElementGuid>5e479e6a-63e6-4772-9c69-bd6975452ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya bersedia dihubungi untuk mendapatkan informasi selanjutnya dari Sequis'])[1]/following::button[1]</value>
      <webElementGuid>6470cdb0-7c98-403e-ab24-aaa17f0bddd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Silakan pilih --'])[4]/following::button[1]</value>
      <webElementGuid>86b1e665-bd27-4871-a411-58fcb33e441a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF sudah dikirimkan ke email Anda'])[1]/preceding::button[2]</value>
      <webElementGuid>b02843ef-31ac-4156-8968-e3c47b7e2a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terima Kasih telah menghubungi Kami'])[1]/preceding::button[2]</value>
      <webElementGuid>bbee5f4e-991a-47d1-aa9e-f7138accd1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAPATKAN SEKARANG']/parent::*</value>
      <webElementGuid>677a9153-1d95-49ff-8da6-c1b5a4b84ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[7]/div/button</value>
      <webElementGuid>cd331a6d-1a46-49a9-931f-15b23d68c67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save-financial' and @type = 'submit' and (text() = 'DAPATKAN SEKARANG' or . = 'DAPATKAN SEKARANG')]</value>
      <webElementGuid>961add7c-a239-4bfc-91a0-a851bc8a616b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
