<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Sequis - Financial Calculator</name>
   <tag></tag>
   <elementGuidId>38bcb2c4-7f13-4985-9d27-2cc9db0b8a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exampleModalLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='exampleModalLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>8576e2c4-74a3-49e8-a332-2017be0ec93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>64372550-c315-46a9-9e48-cd36d178cbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleModalLabel</value>
      <webElementGuid>cea14f2a-4d56-47fb-8625-b4b029528684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sequis - Financial Calculator</value>
      <webElementGuid>440fe0c0-66c5-4a41-8a05-1af4a8512a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exampleModalLabel&quot;)</value>
      <webElementGuid>2ec0eed6-53a8-4f83-9a3f-6c4510ff7b8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='exampleModalLabel']</value>
      <webElementGuid>3e340380-b58e-4ef4-adc2-5ac46be75659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calculatorModal']/div/div/div/h4</value>
      <webElementGuid>f994fec5-9ec3-451a-a315-e0c9c9f445f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/following::h4[1]</value>
      <webElementGuid>8d81a4af-50f9-4576-9d39-ff7aba4877ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan Kode Keamanan'])[1]/following::h4[1]</value>
      <webElementGuid>c41690a4-4a24-4d85-a039-4030bc9c6c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/preceding::h4[1]</value>
      <webElementGuid>0cfde4ab-4c46-48b0-85b6-b48b0b447593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telepon Genggam:'])[1]/preceding::h4[1]</value>
      <webElementGuid>2f47afdc-667e-4761-9ab0-0486a0167972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sequis - Financial Calculator']/parent::*</value>
      <webElementGuid>16f2cb75-b731-4915-a481-f5504a4fe881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/h4</value>
      <webElementGuid>11b31639-7d5b-447c-a073-28f4efdfaa96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'exampleModalLabel' and (text() = 'Sequis - Financial Calculator' or . = 'Sequis - Financial Calculator')]</value>
      <webElementGuid>9efaf16c-c0cc-47b4-9c35-8ed522dd5d29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
