<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Combobox Hubungi</name>
   <tag></tag>
   <elementGuidId>e4d08b3e-b186-4ed3-a29d-f0a8c4f538fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bersedia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bersedia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51a7641a-cbc0-4b11-845a-4b88e95d5f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>1f4d9724-9a9d-4bf8-b198-b71b8959862b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6f2f9bc5-567a-4f56-bf01-4e6e0be76a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bersedia</value>
      <webElementGuid>3280515d-75a7-4edc-80b9-c2bbed4fd8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bersedia</value>
      <webElementGuid>3661ff5a-e72f-4342-846d-cb846a720bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bersedia&quot;)</value>
      <webElementGuid>274a68c2-2084-4c3c-a2a1-22b5e3c7e598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bersedia']</value>
      <webElementGuid>1c471761-b4ca-48ea-a6e9-af0878222d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert-financial']/div[6]/span/input</value>
      <webElementGuid>87d4e537-23ca-47ef-ac49-280d3e2df450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/input</value>
      <webElementGuid>5b203069-f270-40cc-a0a2-02f325fe71e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'bersedia' and @id = 'bersedia']</value>
      <webElementGuid>dc3d8387-cebc-428b-839a-f1e8996aa6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
