<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dana Pensiun</name>
   <tag></tag>
   <elementGuidId>07e07841-e44f-4ed7-bf53-44e111b17e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.accordion-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='col1']/div/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dfd932e3-974b-42c8-977b-c5fedce50e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-toggle</value>
      <webElementGuid>dae8ebcc-95a0-4a92-843f-74e7a6dd595f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>423704db-af86-4234-98fe-c769605792e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>137d6321-aee8-4f78-86af-3a6fe670acd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapse1</value>
      <webElementGuid>81882724-0edb-4332-970c-369a7fb5d63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Dana Pensiun                                    </value>
      <webElementGuid>bd1a5709-7377-47d1-a633-10b688d70efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col1&quot;)/div[@class=&quot;panel-heading active&quot;]/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;accordion-toggle&quot;]</value>
      <webElementGuid>754a989f-350f-48ed-99af-18fc43e489b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='col1']/div/h4/a</value>
      <webElementGuid>7faeeece-4741-4c7d-ad58-4f6888ca2443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dana Pensiun')])[4]</value>
      <webElementGuid>4a753304-5425-41f5-abf6-7c7b4de27519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dana Pensiun'])[7]/following::a[1]</value>
      <webElementGuid>7e379d66-72ff-4ef4-add1-478d04743a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dana Pensiun'])[6]/following::a[1]</value>
      <webElementGuid>0772d7e6-24d1-4da8-b720-39a5171d2f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dana Pensiun'])[9]/preceding::a[1]</value>
      <webElementGuid>ba5d5f6d-a563-4b84-8ff2-66db7121c000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asuransi Retirement Life Plan'])[1]/preceding::a[1]</value>
      <webElementGuid>07527410-6964-4ed9-8cdf-01a38b13f92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#collapse1')]</value>
      <webElementGuid>5b9cfb2e-0794-4eff-b177-000d025387a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a</value>
      <webElementGuid>0377fa61-21d4-4914-9def-8965186f46fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#collapse1' and (text() = '
                                        Dana Pensiun                                    ' or . = '
                                        Dana Pensiun                                    ')]</value>
      <webElementGuid>54df0734-acf0-415c-974b-bd5140e10003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
